name: Generate


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
    inputs:
      url:
        description: 'Stock ROM Url'     
        required: true
        default: 'None'

jobs:
  Generate:
    runs-on: ubuntu-latest

    steps: 
      - name: Setup Python
        uses: actions/setup-python@v2.3.1
        with:
          python-version: '3.9'
          architecture: 'x64'
      - run: python -m pip install twrpdtgen
      - uses: actions/checkout@v2    
      - name: Required package Install
        run: sudo apt-get install wget cpio
      - name: Stock ROM Files Downalod
        run: wget https://temp.sh/bKUpb/boot.img
      - name: TWRP Device Tree Generate
        run: |
         ls
         python -m twrpdtgen recovery.img
         
      - uses: actions/upload-artifact@v2
        with:
          name: Twrp Device Tree
          path: output/*
#       - uses: actions/upload-artifact@v2
#         with:
#           name: Boot Image
#           path: boot.img
#       - uses: actions/upload-artifact@v2
#         with:
#           name: Recovery Image
#           path: recovery.img
          

         
